### ISSUE TITLE
Can't add new subreddits through either the search bar or the  '+' button - "Something went wrong" Error

### ISSUE THREAD

**Issue by ThatFunnyGuyver** [andrasferenczi/vitrina#13]
_Steps to reproduce_:

- use the search bar or '+' button to add a new subreddit.

_Expected Results_:
Subreddit's found and able to be added to Muzei.

_Actual Results_:
"Something went wrong" Error prompt pops up for every character input to the search bar.

**Comment by ravem** [comment]
Same problem.

**Comment by ThatFunnyGuyver** [comment]
Fixes were applied in the latest PR merge. Will close the issue, once tested.

**Comment by ThatFunnyGuyver** [comment]
v35 looks amazing. Search bar and + sign both work. Looks fixed. Issue closed.

**Comment by andrasferenczi** [comment]
@ThatFunnyGuyver Cool! Great to hear that!
